### ISSUE TITLE
ARM image

### ISSUE THREAD

**Issue by alumi** [xcoo/clj-lint-action#5]

**Comment by niyarin** [comment]
- Clj-kondo image( https://hub.docker.com/r/cljkondo/clj-kondo/tags) does not support ARM architecture.
- Clj-kondo install script (https://github.com/clj-kondo/clj-kondo/blob/master/script/install-clj-kondo) does not support ARM.

**Comment by niyarin** [comment]
memo
- ghcr.io/graalvm/native-image (arm) can't do tar tar.gz.
    - Can avoid this by using gunzip & tar.
- On Arm, script with /usr/bin/env shebang only looks at the first value of $PATH
- On Arm, Installing native-image using gu with community ce image fails
    - use ghcr.io/graalvm/native-image

**Comment by niyarin** [comment]
memo
current dockerfile result.
https://github.com/xcoo/clj-lint-action/commit/3136fe608dac9d04f276f47fd41574e676b7685f
```
 Warning: warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /lint-action-clj/hs_err_pid34.log
```

**Comment by athos** [comment]
Which environment do you use to build the image? I tried on my local environment, but could not reproduce the error.

I found the following issue reporting a similar error:

- https://github.com/adoptium/containers/issues/215

And this comment on the issue describes how the error occurs:

- https://github.com/adoptium/containers/issues/215#issuecomment-1142046045

According to it, the combination usage of recent Linux distributions (including Ubuntu Jammy Jellyfish) which use the `clone3` syscall, and a slightly older version of Docker engine (< 20.10.16) seems to cause the error (I'm using 20.10.17, btw).

I'm not sure if you're getting the same error as the above one, but how about first checking the version of the Docker engine you are using to build the Docker image and updating it if using a version older than 20.10.16?

**Comment by niyarin** [comment]
Thank you for the information.
As you said, the version of docker is old, so I will try to update it.

I built this image on a computer with Intel CPU with Ubuntu 21.04 installed.
```
$ docker --version
Docker version 20.10.12, build e91ed57
$ docker buildx version
github.com/docker/buildx v0.7.1-docker 05846896d149da05f3d6fd1e7770da187b52a247
```
