### ISSUE TITLE
Newer JDK version

### ISSUE THREAD

**Issue by alumi** [xcoo/clj-lint-action#9]
[`lein eastwood` can report usages of deprecated APIs with the `:deprecations` linter](https://github.com/jonase/eastwood#deprecations).

```
src/cljam/io/util/bgzf.clj:38:31: deprecations {:kind :new}: Constructor 'public java.net.URL(java.lang.String) throws java.net.MalformedURLException' is deprecated.
```
The newer versions of JDK contain more deprecated APIs. For example, [the API shown above is deprecated since JDK 20](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/net/URL.html#%3Cinit%3E(java.lang.String)).
I think it is useful to have clj-lint-action to report more deprecation warnings to be able to notice such usages earlier.

**Comment by niyarin** [comment]
(memo)
There is a clojure Docker image that includes JDK20.
For example, `clojure:temurin-20-tools-deps-jammy`.
